name: No cache

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Go Build Cache for Docker
        id: cache
        uses: actions/cache@v3
        with:
          path: go-build-cache
          key: go-docker-build-cache-${{ hashFiles('**/*.sum') }}

      - name: inject go-build-cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "go-build-cache": "/go/pkg/mod"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: build
        run: docker buildx build . -f ms/hello/Dockerfile.cache -t gha-go-monorepo-hello --load

