name: No cache

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: docker build . -f ms/hello/Dockerfile -t gha-go-monorepo-hello

